backend:
  name: git-gateway
  branch: master

media_folder: 'public/uploads'
public_folder: 'uploads'

collections:
  - name: 'homepage'
    label: 'Home Page'
    folder: 'public/content/'
    create: true
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'homepage' }
      - { label: 'Hero Heading', name: 'heroHeading', widget: 'string', required: true }
      - { label: 'Hero Subheading', name: 'heroSubheading', widget: 'string' }
