backend:
  name: git-gateway
  branch: master

media_folder: 'public/uploads'
public_folder: 'uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'public/content/pages'
    create: true
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'home' }
      - { label: 'Heading', name: 'heading', widget: 'string', required: true }
      - { label: 'Subheading', name: 'subheading', widget: 'string' }
      - { label: 'Hero Image (small)', name: 'heroImageSm', widget: 'image' }
      - { label: 'Hero Image (medium)', name: 'heroImageMed', widget: 'image' }
      - { label: 'Hero Image (large)', name: 'heroImageLg', widget: 'image' }
      
  - name: "journal"
    label: "Journal Entries"
    folder: "public/content/journal"
    create: true
    slug: "{{month}}-{{day}}-{{year}}_{{slug}}"
    format: 'json'
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "journal-entry" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Featured Image", name: "featureImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "public/content/testimonials"
    create: true
    slug: "{{month}}-{{day}}-{{year}}_{{slug}}"
    format: 'json'
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Testimony", name: "testimony", widget: "string" }